### ISSUE TITLE
absence of link to biological process

### ISSUE THREAD

**Issue by proccaserra** [jamesaoverton/obi-experiment#4]
Hi James,

The one thing I find missing from the representation is the 'why' for performing such an assay:

Ideally, all OBI assays should be linked to some biological process.

Having a link to 'glucose homeostasis' process (http://amigo.geneontology.org/amigo/term/GO:0042593) is a much needed addition.

This pattern for assays has been agreed and we could used 'is_proxy_for' some 'biological process' linking to the 'information content entity' , here a 'scalar measurement datum' output of assay.

This is what I have used to define 'glucose tolerance test' (http://purl.obolibrary.org/obo/OBI_0000721) in OBI a few years back.

As the figure is due an edit, it is the right moment.

best wishes

Philippe

**Comment by jamesaoverton** [comment]
I agree with you, Philippe. Unfortunately, this is too big a change to make during the final push to get the OBI paper out (which is already **long** overdue). 

I will make this improvement to the example after we're done with the manuscript.
